name: Auto-update AUR package

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  aur:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Install dependencies
        run: pacman -Sy --noconfirm base-devel git sudo

      - name: Create non-root user and setup
        run: |
          useradd -m auruser
          echo 'auruser ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/auruser
          sudo -u auruser mkdir -p /home/auruser/.ssh
          sudo -u auruser mkdir -p /home/auruser/aur-repo

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@jellyplayer"

      - name: Get short commit hash
        id: vars
        run: echo "commit_hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

      - name: Update permissions for auruser
        run: |
          sudo chown -R auruser:auruser aur
          sudo chmod -R u+rw aur

      - name: Update PKGBUILD and regenerate .SRCINFO
        run: |
          sudo -u auruser bash -c "cd aur && sed -i 's/^pkgver=.*/pkgver=${{ steps.vars.commit_hash }}/' PKGBUILD && makepkg --printsrcinfo > .SRCINFO"

      - name: Push to AUR
        run: |
          sudo -u auruser mkdir -p /home/auruser/.ssh
          echo "${{ secrets.AUR_SSH_KEY }}" | sudo -u auruser tee /home/auruser/.ssh/id_ed25519 > /dev/null
          sudo -u auruser chmod 600 /home/auruser/.ssh/id_ed25519
          sudo -u auruser ssh-keyscan aur.archlinux.org >> /home/auruser/.ssh/known_hosts

          sudo -u auruser git clone ssh://aur@aur.archlinux.org/jellyplayer-git.git /home/auruser/aur-repo
          sudo -u auruser cp aur/* /home/auruser/aur-repo/
          cd /home/auruser/aur-repo

          sudo -u auruser git add PKGBUILD .SRCINFO
          sudo -u auruser git commit -m "Update to commit ${{ steps.vars.outputs.commit_hash }}"
          sudo -u auruser git push
